### ISSUE TITLE
Can't build with latest npm/cargo on ubuntu 20.04

### ISSUE THREAD

**Issue by MajickTek** [Xiphoseer/paradox-typed-db#1]
Following the instructions I attempted to install paradox from npm.

I received this after a bunch of successful download messages:
```
error: failed to run custom build command for `paradox-typed-db v0.1.0 (https://github.com/Xiphoseer/paradox-typed-db.git#b782ac83)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installbaDhjd/release/build/paradox-typed-db-44ed5f8046450381/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/git/checkouts/paradox-typed-db-aba9554673c5c7a8/b782ac8/build.rs:283:11
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `paradox-server v0.1.0 (https://github.com/Xiphoseer/lu-res-api-server.git?branch=main#979e995d)`, intermediate artifacts can be found at `/tmp/cargo-installbaDhjd`

Caused by:
  build failed
```

system info:
NPM: 6.14.4
cargo: 1.53.0
python (if that matters): 3.8.10

Ill give any more info if necessary.

It could be just a permission issue for some file but im not sure

**Comment by Xiphoseer** [comment]
I just moved the issue to the repo that actually contains the broken code. Commit 032830e should solve both problems, i.e. both just printing a warning when `rustfmt` isn't found and the lifetime issue. It looks like the compiler is smart enough to derive the correct lifetimes from Rust 1.56.0 onwards (I'm usually on stable), but it doesn't hurt to be just that little bit more explicit to support the older compiler versions like the ones that ship with ubuntu by default.

**Comment by Xiphoseer** [comment]
Closing this because I downloaded Rust 1.54.0, compiled paradox server with it once before the change which reproduced the error and once after the change which worked, so I'm reasonably certain it's actually solved. LMK if there are any issues that remain.
